name: 'git-rev-parse-action'
description: 'git rev-parse action'
author: 'kyo-ago'

inputs:
  target:
    description: ''
    required: true

outputs:
  cache-hit:
    description: ''
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - id: run
      run: |
        FILE="${RANDOM}.hash"
        echo `
          echo "${{ inputs.target }}" | while read -r line; do
            if [ "$line" != "" ]; then
              git rev-parse HEAD:$line
            fi
          done | tr '\r\n' ' ' | tr '\n' ' '
        ` > $FILE
        echo "::set-output name=file::$FILE"
      shell: bash
    - id: cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.run.outputs.file }}
        key: ${{ hashFiles(steps.run.outputs.file) }}
