name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./
        id: action
        with:
          target: action.yml
      - run: echo "${{ steps.action.outputs.cache-hit }}"

      - uses: ./
        id: multi
        with:
          target: |
            action.yml
            README.md
      - run: echo "${{ steps.multi.outputs.cache-hit }}"
